# Generated by Django 3.2.6 on 2022-01-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('bio', models.TextField(max_length=1000, null=True)),
                ('school', models.CharField(max_length=70)),
                ('college', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='author')),
            ],
        ),
    ]
